Update installation.md
https://github.com/Sitecore/Sitecore.Demo.Platform being cloned to C:\projects\Sitecore.Demo.Platform\items is required by the current version of docker-compose.override.yml, otherwise `docker-compose up -d` will fail with error message:
```
ERROR: for sitecore-xp0_cm_1  Cannot create container for service cm: invalid volume specification: 'C:\projects\Sitecore.Demo.Platform\items:c:\items:rw': invalid mount config for type "bind": bind source path does not exist: c:\projects\sitecore.demo.platform\items

ERROR: for cm  Cannot create container for service cm: invalid volume specification: 'C:\projects\Sitecore.Demo.Platform\items:c:\items:rw': invalid mount config for type "bind": bind source path does not exist: c:\projects\sitecore.demo.platform\items
ERROR: Encountered errors while bringing up the project.
```